yagna:
#  api_url: "http://localhost:7465"
#  gsb_url: "http://localhost:9999"
  app_key: "$YAGNA_APPKEY"
  subnet_tag: "public"


payment:
  budget: 1.0  # GLM
  driver: "erc20"
  network: "goerli"

#limits:
#  startup_timeout: 300  # timeout for the provisioning of the app (seconds)
#  max_running_time: 1200  # the maximum running time for the app (seconds)
